# .github/workflows/dart.yml

name: Dart CI

on:
  pull_request:
    branches: [production, development]
  push:
    branches: [production, development]
  workflow_dispatch:

jobs:
  analyze_and_test:
    name: Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          cd example && flutter pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run analyzer
        run: flutter analyze

      - name: Run package tests
        run: flutter test

      - name: Run example app tests
        run: flutter test example/test


      - name: Publish to pub.dev
        run: dart pub publish --force
