# .github/workflows/dart.yml

name: Dart CI & Publish

on:
  pull_request:
    branches: [production, development]
  push:
    branches: [development, production]
  workflow_dispatch:

jobs:
  analyze_and_test:
    name: Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          cd example && flutter pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run analyzer
        run: flutter analyze

      - name: Run package tests
        run: flutter test

      - name: Run example app tests
        run: flutter test example/test

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/production'
    needs: analyze_and_test
    permissions:
      id-token: write # Required for secure pub.dev authentication
      contents: read
    runs-on: ubuntu-latest
    name: Deploy to pub.dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Publish to pub.dev
        run: dart pub publish --force

